const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, '../app/static/app.js'), 'utf8');
const start = source.indexOf('function stockForecastCurveSvg(');
const end = source.indexOf('\nfunction ', start + 10);
const context = vm.createContext({safe: value => String(value ?? ''), money: (value, digits=2) => Number(value).toFixed(digits)});
vm.runInContext(source.slice(start, end), context);
const point = (day, low, high, validated=true) => ({trading_day:day, p10:low-20, p25:low, p50:(low+high)/2, p75:high, p90:high+20, validated, basis:validated?'CALIBRATED_BASELINE':'HISTORICAL_BASELINE_REFERENCE'});
const period = days => ({horizon_trading_days:days, status:'AVAILABLE', validation:{gate_passed:true,central_50_coverage_gate:true,central_50_coverage:.4,wide_80_coverage:.8,evaluation_points:30}});
const fixture = {symbol:'test', history_curve:[{date:'2026-09-08',price:410},{date:'2026-09-09',price:412.22}],
  forecast_curve:[{...point(0,412.22,412.22),p10:412.22,p90:412.22},point(1,90000,99999,false),point(5,386.49,449.21),point(21,321.25,565.61),point(252,100000,200000,false)],
  timeframes:[period(5),period(21)],validated_horizon_trading_days:21};
const original=JSON.stringify(fixture);
const html=context.stockForecastCurveSvg(fixture);
const main=html.split('<details')[0];
assert.match(main,/data-horizon-days="5"/);
assert.match(main,/386\.49—449\.21/);
assert.match(main,/40\.0%/);
assert.match(main,/30 个检验样本/);
assert.match(main,/forecast-band-likely/);
assert.doesNotMatch(main,/forecast-band-wide/);
assert.match(html,/<details class="audit-details"><summary>查看至 21/);
assert.match(html,/data-forecast-view="wide" data-horizon-days="21"/);
assert.doesNotMatch(html,/99999|200000/);
assert.equal(JSON.stringify(fixture),original,'display must not change calibrated values');
const median=main.match(/<polyline class="forecast-median" points="([^"]+)"/)[1];
assert.equal(median.split(' ').length,2,'only current and checked endpoint may be connected');
const failedCore=structuredClone(fixture);
failedCore.timeframes.forEach(p=>p.validation.central_50_coverage_gate=false);
const fallback=context.stockForecastCurveSvg(failedCore).split('<details')[0];
assert.match(fallback,/forecast-band-wide/);
assert.doesNotMatch(fallback,/forecast-band-likely/);
const unchecked=structuredClone(fixture);
unchecked.timeframes.forEach(p=>p.validation.gate_passed=false);
const noForecast=context.stockForecastCurveSvg(unchecked);
assert.doesNotMatch(noForecast,/<polygon|class="forecast-median"/);
assert.match(noForecast,/没有通过检验/);
console.log('PASS: short-term core view, intact intervals, empirical coverage, expandable wide view, exclusion of unvalidated points.');
