const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, '../app/static/app.js'), 'utf8');
const start = source.indexOf('function stockForecastCurveSvg(');
const end = source.indexOf('\nfunction ', start + 10);
const context = vm.createContext({safe: value => String(value ?? ''), money: (value, digits=2) => Number(value).toFixed(digits)});
vm.runInContext(source.slice(start, end), context);
const point = (day, low, high, validated=true) => ({trading_day:day, p10:low-20, p25:low, p50:(low+high)/2, p75:high, p90:high+20, validated, basis:validated?'CALIBRATED_BASELINE':'HISTORICAL_BASELINE_REFERENCE'});
const period = days => ({horizon_trading_days:days, status:'AVAILABLE', validation:{gate_passed:true,central_50_coverage_gate:true,central_50_coverage:.4,wide_80_coverage:.8,evaluation_points:30}});
const fixture = {symbol:'test', history_curve:[{date:'2026-09-08',price:410},{date:'2026-09-09',price:412.22}],
  forecast_curve:[{...point(0,412.22,412.22),p10:412.22,p90:412.22},point(1,90000,99999,false),point(5,386.49,449.21),point(21,321.25,565.61),point(252,100000,200000,false)],
  timeframes:[period(5),period(21)],validated_horizon_trading_days:21};
const original=JSON.stringify(fixture);
const html=context.stockForecastCurveSvg(fixture),main=html.split('<details')[0];
assert.match(main,/data-horizon-days="5"/);
assert.match(main,/386\.49—449\.21/);
assert.match(main,/40\.0%/);assert.match(main,/30 个检验样本/);
assert.match(main,/forecast-band-likely/);assert.doesNotMatch(main,/forecast-band-wide/);
assert.match(html,/展开历史全貌与至 21/);
assert.match(html,/data-forecast-view="wide" data-horizon-days="21"/);
assert.doesNotMatch(html,/99999|200000/);
assert.equal(JSON.stringify(fixture),original,'rendering must not change any forecast values');
const coordinates=(markup,cls)=>markup.match(new RegExp('<polyline class="'+cls+'" points="([^"]+)"'))[1].split(' ').map(p=>p.split(',').map(Number));
const history=coordinates(main,'history-line'),future=coordinates(main,'forecast-median');
const split=Number(main.match(/data-split-x="([^"]+)"/)[1]);
assert.equal(history.at(-1)[0],split);
assert.deepEqual(history.at(-1),future[0],'history and forecast must meet at the same time and price coordinate');
assert.ok(history.slice(0,-1).every(p=>p[0]<split),'past must stay left of divider');
assert.ok(future.slice(1).every(p=>p[0]>split),'forecast must stay right of divider');
assert.equal(future.length,2,'connect only actual origin and checked endpoint, never invent daily prices');
assert.match(main,/已有走势/);assert.match(main,/未来预测/);
assert.match(main,/共用价格纵轴/);assert.match(main,/不代表逐日预测/);
assert.match(main,/data-axis="history-and-forecast"/);
const failedCore=structuredClone(fixture);failedCore.timeframes.forEach(p=>p.validation.central_50_coverage_gate=false);
const fallback=context.stockForecastCurveSvg(failedCore).split('<details')[0];
assert.match(fallback,/forecast-band-wide/);assert.doesNotMatch(fallback,/forecast-band-likely/);
const unchecked=structuredClone(fixture);unchecked.timeframes.forEach(p=>p.validation.gate_passed=false);
const noForecast=context.stockForecastCurveSvg(unchecked);
assert.doesNotMatch(noForecast,/<polygon|class="forecast-median"/);
assert.match(noForecast,/没有通过检验/);assert.match(noForecast,/class="history-line"/);
const terminal21={symbol:'002651',history_curve:[{date:'2026-09-08',price:8.9},{date:'2026-09-09',price:8.81}],
  forecast_curve:[point(0,8.81,8.81),{...point(21,8.149,9.342),p50:8.716}],timeframes:[period(21)]};
const terminalHtml=context.stockForecastCurveSvg(terminal21).split('<details')[0];
assert.match(terminalHtml,/8.149—9.342/);assert.match(terminalHtml,/¥8.716/);
assert.match(terminalHtml,/未来预测 · 21 个交易日/);
assert.deepEqual(coordinates(terminalHtml,'history-line').at(-1),coordinates(terminalHtml,'forecast-median')[0]);
assert.match(terminalHtml,/<polygon class="forecast-band-likely"/);
console.log('PASS: history left, forecast right, continuous common price scale, actual nodes only, intact intervals, validated horizons and history-only fallback.');
